sudo: required
services:
  - docker

before_install:
  - docker build -t taraspyoneer/react-test -f ./client/Dockerfile.dev ./client

# script:
  - docker run taraspyoneer/react-test npm test -- --coverage

after_success:
  - docker build -t taraspyoneer/multi-client ./client
  - docker build -t taraspyoneer/multi-nginx ./nginx
  - docker build -t taraspyoneer/multi-server ./server
  - docker build -t taraspyoneer/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push taraspyoneer/multi-client
  - docker push taraspyoneer/multi-nginx
  - docker push taraspyoneer/multi-server
  - docker push taraspyoneer/multi-worker
